### ISSUE TITLE
make failing to build

### ISSUE THREAD

**Issue by orlikoski** [target/attack-navigator-docker#1]
Following the instructions in the README I've done the following

```
cd attack-navigator-docker
git submodule update --init --recursive
make > output.log 2>&1
```

It resulted in a build errror. 

Attached is `output.log`
[output.log](https://github.com/target/attack-navigator-docker/files/2438799/output.log)

**Comment by orlikoski** [comment]
Tried this process and still failing (logs attached)
```
git clone https://github.com/target/attack-navigator-docker.git
cd attack-navigator-docker
git submodule update --init --recursive
rm attack-navigator/package-lock.json
make > output2.log 2>&1
```
[output2.log](https://github.com/target/attack-navigator-docker/files/2438866/output2.log)

**Comment by tnvo** [comment]
Through the logs, it seems like it had some error with some node packages... A few questions:
* Did you update node/angular-cli?
* Are you on a corporate network or on a network that could potentially block certain sites?

I just tested this on a fresh VM step by step as in the README and it seemed to work:

```
brew install node angular-cli

git clone --recurse-submodules https://github.com/target/attack-navigator-docker.git

cd attack-navigator-docker

make

make run
```

I have also tried to run, it did not give any output, but worked for me when going to localhost:80:
```
docker run -it -p 80:80 --name attacknav davidjbianco/attacknav:latest
```

Could you delete the current repo and try with a fresh clone (vs. the git update)?

I can comb through the logs files a bit more later and let you know if I find anything new!

**Comment by orlikoski** [comment]
Thanks for the help and I've tried all of the things you've mentioned. Here are some results
```
~/Development/attack-navigator-docker master * brew install node angular-cli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/cask).
==> Updated Formulae
fpc                                                                                                    landscaper

Warning: node 10.11.0 is already installed and up-to-date
To reinstall 10.11.0, run `brew reinstall node`
Warning: angular-cli 6.2.3 is already installed and up-to-date
To reinstall 6.2.3, run `brew reinstall angular-cli`
```
followed by
```
~/Development/attack-navigator-docker master * cd ..
~/Development rm -rf attack-navigator-docker/
~/Development git clone --recurse-submodules https://github.com/target/attack-navigator-docker.git
Cloning into 'attack-navigator-docker'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 24 (delta 5), reused 12 (delta 2), pack-reused 0
Unpacking objects: 100% (24/24), done.
Submodule 'attack-navigator' (https://github.com/mitre/attack-navigator.git) registered for path 'attack-navigator'
Cloning into '/Users/alano/Development/attack-navigator-docker/attack-navigator'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 1694 (delta 27), reused 34 (delta 16), pack-reused 1634
Receiving objects: 100% (1694/1694), 4.90 MiB | 6.18 MiB/s, done.
Resolving deltas: 100% (1276/1276), done.
Submodule path 'attack-navigator': checked out '24d9187dea19b75b32858302be24c0f92d008834'
```
Followed by `make` and it fails so not going to run `make build`(logs attached)
```
cd attack-navigator-docker

make > output3.log 2>&1
```

[output3.log](https://github.com/target/attack-navigator-docker/files/2438963/output3.log)

**Comment by tnvo** [comment]
I think most of the problem are right here:
```
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.11.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.11.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 

```

vs. successful install:
```
> node install

[fsevents] Success: "/Users/xxx/Desktop/X/OS/attack-navigator-docker/attack-navigator/nav-app/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.7.2 install /Users/xxx/Desktop/X/OS/attack-navigator-docker/attack-navigator/nav-app/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-57_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/xxx/Desktop/X/OS/attack-navigator-docker/attack-navigator/nav-app/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Caching binary to /Users/xxx/.npm/node-sass/4.7.2/darwin-x64-57_binding.node


```

I did some initial research. Seems like something is off with node version. I'm running node v8.11.4. Sounds like there are a lot of cases where node-gyp source compile failing with node v10. (using nvm but you can also use `n` if you prefer that!)

```
nvm install 8.11.4
nvm use 8.11.4

# and installing node-gyp globally:
npm install -g node-gyp
```

Thanks for letting us know the issues. Node can be picky sometimes. 🤕

**Comment by DavidJBianco** [comment]
The problem is that the ATT&CK Navigator module has a dependency on `fsevents` v1.1.3.  It's trying to pull down precompiled binaries for your version of `node.js` (10.11.0), but they're not available. I had a similar issue.  `fsevents` v1.1.3 is explicitly listed in the module's `package-lock.json` file, and I think that version is just too old to have precompiled binaries for newer versions of `node.js`.  

Two workarounds you could try:

* Downgrade your version of `node.js` to something fairly old, when they were still producing v1.1.3 binaries for `fsevents`
* Remove the `attack-navigator/nav-app/package-lock.json` file and restart the build. It'll fetch a newer version of fsevents. This is the one I tried and it worked for me.

I opened an issue with the module, which you can see [here](https://github.com/mitre/attack-navigator/issues/61) if you like.

**Comment by orlikoski** [comment]
The nvm install 8.1.1.4 got it working for me.

Thank you for all the help
