### ISSUE TITLE
Errors on make

### ISSUE THREAD

**Issue by mark1973ryan** [target/attack-navigator-docker#5]
Hi,

Seems the following doesn't exist for a start. I get a raft of errors but can you suggest a replacement for the first?

https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-64_binding.node

Full error report.

docker pull node:"10-slim"
10-slim: Pulling from library/node
Digest: sha256:ce0b8ec37c669bb12da1683a265a2aa6f85cdd7a692d959f7c48e8c26cc37585
Status: Image is up to date for node:10-slim
docker.io/library/node:10-slim
docker pull nginx:stable-alpine
stable-alpine: Pulling from library/nginx
Digest: sha256:5057451e461dda671da5e951019ddbff9d96a751fc7d548053523ca1f848c1ad
Status: Image is up to date for nginx:stable-alpine
docker.io/library/nginx:stable-alpine
git submodule init
git submodule update
docker run -it --rm -v `pwd`/attack-navigator:/attack-navigator node:"10-slim" /bin/sh -c 'cd /attack-navigator/nav-app && npm install && npm run build'

> node-sass@4.7.2 install /attack-navigator/nav-app/node_modules/node-sass
> node scripts/install.js

**Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-64_binding.node": 

HTTP error 404 Not Found**

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.7.2 postinstall /attack-navigator/nav-app/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /attack-navigator/nav-app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/attack-navigator/nav-app/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.19.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/attack-navigator/nav-app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/attack-navigator/nav-app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/attack-navigator/nav-app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/attack-navigator/nav-app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/attack-navigator/nav-app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/attack-navigator/nav-app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/attack-navigator/nav-app/node_modules/which/which.js:13:12)\n    at F (/attack-navigator/nav-app/node_modules/which/which.js:68:19)\n    at E (/attack-navigator/nav-app/node_modules/which/which.js:80:29)\n    at /attack-navigator/nav-app/node_modules/which/which.js:89:16\n    at /attack-navigator/nav-app/node_modules/isexe/index.js:42:5\n    at /attack-navigator/nav-app/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/attack-navigator/nav-app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/attack-navigator/nav-app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/attack-navigator/nav-app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/attack-navigator/nav-app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/attack-navigator/nav-app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/attack-navigator/nav-app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /attack-navigator/nav-app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (/attack-navigator/nav-app/node_modules/which/which.js:13:12)\n    at F (/attack-navigator/nav-app/node_modules/which/which.js:68:19)\n    at E (/attack-navigator/nav-app/node_modules/which/which.js:80:29)\n    at /attack-navigator/nav-app/node_modules/which/which.js:89:16\n    at /attack-navigator/nav-app/node_modules/isexe/index.js:42:5\n    at /attack-navigator/nav-app/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/attack-navigator/nav-app/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/attack-navigator/nav-app/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/attack-navigator/nav-app/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/attack-navigator/nav-app/node_modules/which/which.js:80:29)
gyp ERR! stack     at /attack-navigator/nav-app/node_modules/which/which.js:89:16
gyp ERR! stack     at /attack-navigator/nav-app/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /attack-navigator/nav-app/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.18.0-80.4.2.el8_0.x86_64
gyp ERR! command "/usr/local/bin/node" "/attack-navigator/nav-app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /attack-navigator/nav-app/node_modules/node-sass
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 8096 packages in 12.805s
found 300 vulnerabilities (28 low, 88 moderate, 183 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> nav-app@1.0.0 build /attack-navigator/nav-app
> ng build

 92% chunk asset optimizationKilled                                                       
 npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! nav-app@1.0.0 build: `ng build`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the nav-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-27T09_06_48_901Z-debug.log
make: *** [Makefile:7: build] Error 137

**Comment by beerMT** [comment]
Was there a solution to the above? I just ran make and had the same issue...

**Comment by DavidJBianco** [comment]
As did I.  No resolution that I'm aware of.  The issue is actually inside the original attack-navigator app, which is included as a submodule.  I'm checking it out now to see what's up.

**Comment by DavidJBianco** [comment]
Ok, this is now resolved.  I modified the Makefile to make sure `node-sass` was actually installed before building, and everything is working once again.

**Comment by beerMT** [comment]
Thanks @DavidJBianco for the quick response and resolution!
